gait_types: # The used gains are only for testing that the correct set of gains has been loaded.
  sit_gains:
    left_ankle: {p: 10001, i: 0, d: 10}
    left_hip_aa: {p: 10001, i: 0, d: 10}
    left_hip_fe: {p: 10001, i: 0, d: 10}
    left_knee: {p: 10001, i: 0, d: 10}
    right_ankle: {p: 10001, i: 0, d: 10}
    right_hip_aa: {p: 10001, i: 0, d: 10}
    right_hip_fe: {p: 10001, i: 0, d: 10}
    right_knee: {p: 10001, i: 0, d: 10}
  walk_gains:
    left_ankle: {p: 10002, i: 0, d: 10}
    left_hip_aa: {p: 10002, i: 0, d: 10}
    left_hip_fe: {p: 10002, i: 0, d: 10}
    left_knee: {p: 10002, i: 0, d: 10}
    right_ankle: {p: 10002, i: 0, d: 10}
    right_hip_aa: {p: 10002, i: 0, d: 10}
    right_hip_fe: {p: 10002, i: 0, d: 10}
    right_knee: {p: 10002, i: 0, d: 10}
  stand_gains:
    left_ankle: {p: 10003, i: 0, d: 10}
    left_hip_aa: {p: 10003, i: 0, d: 10}
    left_hip_fe: {p: 10003, i: 0, d: 10}
    left_knee: {p: 10003, i: 0, d: 10}
    right_ankle: {p: 10003, i: 0, d: 10}
    right_hip_aa: {p: 10003, i: 0, d: 10}
    right_hip_fe: {p: 10003, i: 0, d: 10}
    right_knee: {p: 10003, i: 0, d: 10}