ignore:
# Ignore packages completely
  - "march_description/.*"
  - "march_launch/.*"
  - "march_shared_resources/.*"

# Ignore test folders
  - "march_gait_scheduler/test/.*"
  - "march_gait_selection/test/.*"
  - "march_safety/test/.*"
  - "march_sound_scheduler/test/.*"
  - "march_state_machine/test/.*"
