gait_types: # The used gains are only for testing that the correct set of gains has been loaded.
  sit_gains:
    rotational_joint: {p: 10001, i: 0, d: 10}
  walk_gains:
    rotational_joint: {p: 10002, i: 0, d: 10}
  stand_gains:
    rotational_joint: {p: 10003, i: 0, d: 10}